from __future__ import annotations

# All UI strings go here. Default language is Macedonian ("mk").
TEXT = {
  "mk": {
    "menu_title": "Cyber Defender: Block & Blast",
    "start_story": "Приказна",
    "settings": "Поставки",
    "achievements": "Достигнувања",
    "credits": "Кредити",
    "quit": "Излез",

    "back": "Назад",
    "language": "Јазик",
    "lang_mk": "Македонски",
    "lang_en": "English",
    "resolution": "Резолуција",
    "fullscreen": "Цел екран",
    "music_vol": "Музика",
    "sfx_vol": "Ефекти",

    "story_map": "Мапа на светови",
    "world_locked": "Заклучено",
    "world_1": "Свет 1: Profile Patrol",
    "world_2": "Свет 2: Password Power",
    "world_3": "Свет 3: Chat Shield",
    "world_4": "Свет 4: Scam Storm",
    "stage": "Ниво",
    "boss": "Бос",

    "hud_score": "Score",
    "hud_combo": "Combo",
    "hud_lives": "Срца",
    "hud_rank": "Rank",
    "hud_wave": "Wave",
    "hud_objective": "Mission",
    "hud_next": "Next",
    "hud_hold": "Hold",
    "pause": "Пауза",
    "resume": "Продолжи",
    "restart": "Од почеток",
    "to_menu": "Мени",
    "main_menu": "Главно мени",

    "mode_story": "Приказна",

    "card_title": "Брза проверка",
    "choice_safe": "Безбедно за споделување",
    "choice_private": "Приватно",
    "choice_never": "Никогаш",
    "card_continue": "Продолжи",
    "card_correct": "Точно!",
    "card_wrong": "Упс…",
    "card_tip": "Совет:",

    "power_shield": "Штит",
    "power_report": "Пријави",
    "power_block": "Блокирај",
    "power_hero": "Cyber Hero",

    "boss_fake_prize": "The Fake Prize Ship",
    "boss_phishing": "The Phishing Mothership",
    "boss_chat": "The DM Magnet",
    "boss_privacy": "The Profile Snatcher",
    "boss_cyber_overlord": "The Cyber Overlord",

    "ach_title": "Достигнувања",
    "ach_locked": "Заклучено",
    "ach_unlocked": "Отклучено",
    "coins": "Монети",
    "xp": "XP",

    "daily_rule": "Дневен предизвик (опционално)",
    "daily_on": "Вклучи",
    "daily_off": "Исклучи",

    "tooltip_hold": "C: Hold парче",
    "tooltip_rotate": "Z/X: Ротирај",
    "tooltip_drop": "Down: Спушти",
  },
  "en": {
    "menu_title": "Cyber Defender: Block & Blast",
    "start_story": "Story",
    "settings": "Settings",
    "achievements": "Achievements",
    "credits": "Credits",
    "quit": "Quit",

    "back": "Back",
    "language": "Language",
    "lang_mk": "Македонски",
    "lang_en": "English",
    "resolution": "Resolution",
    "fullscreen": "Fullscreen",
    "music_vol": "Music",
    "sfx_vol": "SFX",

    "story_map": "World Map",
    "world_locked": "Locked",
    "world_1": "World 1: Profile Patrol",
    "world_2": "World 2: Password Power",
    "world_3": "World 3: Chat Shield",
    "world_4": "World 4: Scam Storm",
    "stage": "Stage",
    "boss": "Boss",

    "hud_score": "Score",
    "hud_combo": "Combo",
    "hud_lives": "Hearts",
    "hud_rank": "Rank",
    "hud_wave": "Wave",
    "hud_objective": "Mission",
    "hud_next": "Next",
    "hud_hold": "Hold",
    "pause": "Paused",
    "resume": "Resume",
    "restart": "Restart",
    "to_menu": "Menu",
    "main_menu": "Main Menu",

    "mode_story": "Story",

    "card_title": "Quick Check",
    "choice_safe": "Safe to Share",
    "choice_private": "Private",
    "choice_never": "Never Share",
    "card_continue": "Continue",
    "card_correct": "Correct!",
    "card_wrong": "Oops…",
    "card_tip": "Tip:",

    "power_shield": "Shield",
    "power_report": "Report",
    "power_block": "Block",
    "power_hero": "Cyber Hero",

    "boss_fake_prize": "The Fake Prize Ship",
    "boss_phishing": "The Phishing Mothership",
    "boss_chat": "The DM Magnet",
    "boss_privacy": "The Profile Snatcher",
    "boss_cyber_overlord": "The Cyber Overlord",

    "ach_title": "Achievements",
    "ach_locked": "Locked",
    "ach_unlocked": "Unlocked",
    "coins": "Coins",
    "xp": "XP",

    "daily_rule": "Daily Challenge (optional)",
    "daily_on": "On",
    "daily_off": "Off",

    "tooltip_hold": "C: Hold piece",
    "tooltip_rotate": "Z/X: Rotate",
    "tooltip_drop": "Down: Soft drop",
  }
}
